project:
  title: "score-models"
  type: book
  output-dir: _site

book:
  title: "A Pedagogical Introduction to Score Models"
  author: Eric J. Ma
  date: "2022-04-21"
  chapters:
    - "index.md"
    - "notebooks/01-score-function.ipynb"
    - "notebooks/02-langevin-dynamics.ipynb"
    - "notebooks/03-noise-scales.ipynb"
  page-footer: "Copyright 2022-present, Eric J. Ma"

bibliography: references.bib

# https://quarto.org/docs/books/
format:
  html:
    theme: cosmo
# site-url: https://ericmjl.github.io/score-models
# repo-url: https://github.com/ericmjl/score-models
# navbar:
#   search: true
